version: "3.9"

services:

  db:
    image: pgvector/pgvector:pg15
    container_name: taxes_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taxes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5434:5432"

  app:
    build: .
    container_name: taxes
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/taxes_db
    ports:
      - "8004:8000"
    env_file:
      - .env
    volumes:
      - ./app/static:/app/static
volumes:
  postgres_data: